namespace: falafel-shop-inc-prod
environment: prod

app:
  image:
    tag: latest # Production release
  replicas: 2  # Higher availability in prod

ingress:
  host: falafel-shop-inc.local  # Production domain
